'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'このクラスは StronglyTypedResourceBuilder クラスが ResGen
'または Visual Studio のようなツールを使用して自動生成されました。
'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
'''<summary>
'''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InputManWin13_Demo.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
    '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property allowdown() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("allowdown", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property allowup() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("allowup", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property bg() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property calendar() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property eraser() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("eraser", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property find() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property fotter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("fotter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property header_b() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("header_b", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property header_g() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("header_g", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property InputMan() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("InputMan", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property mainvisual() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mainvisual", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property menuheader() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("menuheader", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property now() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("now", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property product_logo() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("product_logo", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property question() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("question", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property separator() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("separator", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property stopwatch() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("stopwatch", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
    '''</summary>
    Friend Shared ReadOnly Property today() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("today", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
